# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robot_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#
# Project: 6-DOF Robotic Arm - Author: Luca Obwegs

from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Robot Controller")
        MainWindow.resize(1920, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_uart = QtWidgets.QFrame(self.centralwidget)
        self.frame_uart.setEnabled(True)
        self.frame_uart.setGeometry(QtCore.QRect(0, 100, 960, 100))
        self.frame_uart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_uart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_uart.setObjectName("frame_uart")
        self.input_com_port = QtWidgets.QLineEdit(self.frame_uart)
        self.input_com_port.setGeometry(QtCore.QRect(170, 30, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input_com_port.setFont(font)
        self.input_com_port.setObjectName("input_com_port")
        self.label_serial_port = QtWidgets.QLabel(self.frame_uart)
        self.label_serial_port.setGeometry(QtCore.QRect(40, 30, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_serial_port.setFont(font)
        self.label_serial_port.setObjectName("label_serial_port")
        
        #uart connect
        self.button_connect_uart = QtWidgets.QPushButton(self.frame_uart)
        self.button_connect_uart.setGeometry(QtCore.QRect(800, 15, 141, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_connect_uart.setFont(font)
        self.button_connect_uart.setObjectName("button_connect_uart")
        #self.button_connect_uart.clicked.connect(self.connectUart)

        #uart disconnect
        self.button_disconnect_uart = QtWidgets.QPushButton(self.frame_uart)
        self.button_disconnect_uart.setGeometry(QtCore.QRect(640, 15, 141, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_disconnect_uart.setFont(font)
        self.button_disconnect_uart.setObjectName("button_disconnect_uart")


        self.frame_ts_control_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_ts_control_2.setGeometry(QtCore.QRect(0, 200, 960, 300))
        self.frame_ts_control_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ts_control_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ts_control_2.setObjectName("frame_ts_control_2")
        self.label_ts_control = QtWidgets.QLabel(self.frame_ts_control_2)
        self.label_ts_control.setGeometry(QtCore.QRect(0, 0, 960, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_ts_control.setFont(font)
        self.label_ts_control.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ts_control.setObjectName("label_ts_control")

        #x slider
        self.slider_x = QtWidgets.QSlider(self.frame_ts_control_2)
        self.slider_x.setGeometry(QtCore.QRect(120, 120, 150, 40))
        self.slider_x.setOrientation(QtCore.Qt.Horizontal)
        self.slider_x.setObjectName("slider_x")
        self.label_x = QtWidgets.QLabel(self.frame_ts_control_2)
        self.label_x.setGeometry(QtCore.QRect(40, 120, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(14)

        #x input
        self.label_x.setFont(font)
        self.label_x.setObjectName("label_x")
        self.input_x_axis = QtWidgets.QLineEdit(self.frame_ts_control_2)
        self.input_x_axis.setGeometry(QtCore.QRect(160, 70, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_x_axis.setFont(font)
        self.input_x_axis.setAlignment(QtCore.Qt.AlignCenter)
        self.input_x_axis.setObjectName("input_x_axis")

        #y input
        self.input_y_axis = QtWidgets.QLineEdit(self.frame_ts_control_2)
        self.input_y_axis.setGeometry(QtCore.QRect(480, 70, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_y_axis.setFont(font)
        self.input_y_axis.setAlignment(QtCore.Qt.AlignCenter)
        self.input_y_axis.setObjectName("input_y_axis")

        #y slider
        self.slider_y = QtWidgets.QSlider(self.frame_ts_control_2)
        self.slider_y.setGeometry(QtCore.QRect(440, 120, 150, 40))
        self.slider_y.setOrientation(QtCore.Qt.Horizontal)
        self.slider_y.setObjectName("slider_y")
        self.label_y = QtWidgets.QLabel(self.frame_ts_control_2)
        self.label_y.setGeometry(QtCore.QRect(360, 120, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_y.setFont(font)
        self.label_y.setObjectName("label_y")

        #z input
        self.input_z_axis = QtWidgets.QLineEdit(self.frame_ts_control_2)
        self.input_z_axis.setGeometry(QtCore.QRect(800, 70, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_z_axis.setFont(font)
        self.input_z_axis.setAlignment(QtCore.Qt.AlignCenter)
        self.input_z_axis.setObjectName("input_z_axis")
        self.slider_z = QtWidgets.QSlider(self.frame_ts_control_2)
        self.slider_z.setGeometry(QtCore.QRect(760, 120, 150, 40))
        self.slider_z.setOrientation(QtCore.Qt.Horizontal)
        self.slider_z.setObjectName("slider_z")
        self.label_z = QtWidgets.QLabel(self.frame_ts_control_2)
        self.label_z.setGeometry(QtCore.QRect(680, 120, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_z.setFont(font)
        self.label_z.setObjectName("label_z")
        self.label_theta = QtWidgets.QLabel(self.frame_ts_control_2)
        self.label_theta.setGeometry(QtCore.QRect(350, 230, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_theta.setFont(font)
        self.label_theta.setObjectName("label_theta")
        self.input_phi = QtWidgets.QLineEdit(self.frame_ts_control_2)
        self.input_phi.setGeometry(QtCore.QRect(160, 180, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_phi.setFont(font)
        self.input_phi.setAlignment(QtCore.Qt.AlignCenter)
        self.input_phi.setObjectName("input_phi")
        self.input_psi = QtWidgets.QLineEdit(self.frame_ts_control_2)
        self.input_psi.setGeometry(QtCore.QRect(800, 180, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_psi.setFont(font)
        self.input_psi.setAlignment(QtCore.Qt.AlignCenter)
        self.input_psi.setObjectName("input_psi")
        self.label_psi = QtWidgets.QLabel(self.frame_ts_control_2)
        self.label_psi.setGeometry(QtCore.QRect(700, 230, 51, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_psi.setFont(font)
        self.label_psi.setObjectName("label_psi")
        self.slider_phi = QtWidgets.QSlider(self.frame_ts_control_2)
        self.slider_phi.setGeometry(QtCore.QRect(120, 230, 150, 40))
        self.slider_phi.setOrientation(QtCore.Qt.Horizontal)
        self.slider_phi.setObjectName("slider_phi")
        self.input_theta = QtWidgets.QLineEdit(self.frame_ts_control_2)
        self.input_theta.setGeometry(QtCore.QRect(480, 180, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_theta.setFont(font)
        self.input_theta.setAlignment(QtCore.Qt.AlignCenter)
        self.input_theta.setObjectName("input_theta")
        self.label_phi = QtWidgets.QLabel(self.frame_ts_control_2)
        self.label_phi.setGeometry(QtCore.QRect(40, 230, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_phi.setFont(font)
        self.label_phi.setObjectName("label_phi")
        self.slider_theta = QtWidgets.QSlider(self.frame_ts_control_2)
        self.slider_theta.setGeometry(QtCore.QRect(440, 230, 150, 40))
        self.slider_theta.setOrientation(QtCore.Qt.Horizontal)
        self.slider_theta.setObjectName("slider_theta")
        self.slider_psi = QtWidgets.QSlider(self.frame_ts_control_2)
        self.slider_psi.setGeometry(QtCore.QRect(760, 230, 150, 40))
        self.slider_psi.setOrientation(QtCore.Qt.Horizontal)
        self.slider_psi.setObjectName("slider_psi")
        
        self.button_x_plus = QtWidgets.QPushButton(self.frame_ts_control_2)
        self.button_x_plus.setGeometry(QtCore.QRect(230, 70, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_x_plus.setFont(font)
        self.button_x_plus.setObjectName("button_x_plus")


        self.button_y_plus = QtWidgets.QPushButton(self.frame_ts_control_2)
        self.button_y_plus.setGeometry(QtCore.QRect(550, 70, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_y_plus.setFont(font)
        self.button_y_plus.setObjectName("button_y_plus")
        self.button_z_plus = QtWidgets.QPushButton(self.frame_ts_control_2)
        self.button_z_plus.setGeometry(QtCore.QRect(870, 70, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_z_plus.setFont(font)
        self.button_z_plus.setObjectName("button_z_plus")
        self.button_phi_plus = QtWidgets.QPushButton(self.frame_ts_control_2)
        self.button_phi_plus.setGeometry(QtCore.QRect(230, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_phi_plus.setFont(font)
        self.button_phi_plus.setObjectName("button_phi_plus")
        self.button_theta_plus = QtWidgets.QPushButton(self.frame_ts_control_2)
        self.button_theta_plus.setGeometry(QtCore.QRect(550, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_theta_plus.setFont(font)
        self.button_theta_plus.setObjectName("button_theta_plus")
        self.button_psi_plus = QtWidgets.QPushButton(self.frame_ts_control_2)
        self.button_psi_plus.setGeometry(QtCore.QRect(870, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_psi_plus.setFont(font)
        self.button_psi_plus.setObjectName("button_psi_plus")
        self.button_x_minus = QtWidgets.QPushButton(self.frame_ts_control_2)
        self.button_x_minus.setGeometry(QtCore.QRect(120, 70, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_x_minus.setFont(font)
        self.button_x_minus.setObjectName("button_x_minus")

        self.button_y_minus = QtWidgets.QPushButton(self.frame_ts_control_2)
        self.button_y_minus.setGeometry(QtCore.QRect(440, 70, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_y_minus.setFont(font)
        self.button_y_minus.setObjectName("button_y_minus")
        self.button_z_minus = QtWidgets.QPushButton(self.frame_ts_control_2)
        self.button_z_minus.setGeometry(QtCore.QRect(760, 70, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_z_minus.setFont(font)
        self.button_z_minus.setObjectName("button_z_minus")
        self.button_psi_minus = QtWidgets.QPushButton(self.frame_ts_control_2)
        self.button_psi_minus.setGeometry(QtCore.QRect(760, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_psi_minus.setFont(font)
        self.button_psi_minus.setObjectName("button_psi_minus")
        self.button_theta_minus = QtWidgets.QPushButton(self.frame_ts_control_2)
        self.button_theta_minus.setGeometry(QtCore.QRect(440, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_theta_minus.setFont(font)
        self.button_theta_minus.setObjectName("button_theta_minus")
        self.button_phi_minus = QtWidgets.QPushButton(self.frame_ts_control_2)
        self.button_phi_minus.setGeometry(QtCore.QRect(120, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_phi_minus.setFont(font)
        self.button_phi_minus.setObjectName("button_phi_minus")
        self.frame_js_control = QtWidgets.QFrame(self.centralwidget)
        self.frame_js_control.setGeometry(QtCore.QRect(0, 500, 960, 300))
        self.frame_js_control.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_js_control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_js_control.setObjectName("frame_js_control")
        self.slider_j5 = QtWidgets.QSlider(self.frame_js_control)
        self.slider_j5.setGeometry(QtCore.QRect(440, 230, 150, 40))
        self.slider_j5.setOrientation(QtCore.Qt.Horizontal)
        self.slider_j5.setObjectName("slider_j5")
        self.slider_j6 = QtWidgets.QSlider(self.frame_js_control)
        self.slider_j6.setGeometry(QtCore.QRect(760, 230, 150, 40))
        self.slider_j6.setOrientation(QtCore.Qt.Horizontal)
        self.slider_j6.setObjectName("slider_j6")
        self.label_js_control = QtWidgets.QLabel(self.frame_js_control)
        self.label_js_control.setGeometry(QtCore.QRect(0, 0, 960, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_js_control.setFont(font)
        self.label_js_control.setAlignment(QtCore.Qt.AlignCenter)
        self.label_js_control.setObjectName("label_js_control")
        self.slider_j3 = QtWidgets.QSlider(self.frame_js_control)
        self.slider_j3.setGeometry(QtCore.QRect(760, 120, 150, 40))
        self.slider_j3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_j3.setObjectName("slider_j3")
        self.input_j5 = QtWidgets.QLineEdit(self.frame_js_control)
        self.input_j5.setGeometry(QtCore.QRect(480, 180, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_j5.setFont(font)
        self.input_j5.setAlignment(QtCore.Qt.AlignCenter)
        self.input_j5.setObjectName("input_j5")
        self.label_j1 = QtWidgets.QLabel(self.frame_js_control)
        self.label_j1.setGeometry(QtCore.QRect(30, 120, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_j1.setFont(font)
        self.label_j1.setObjectName("label_j1")
        self.slider_j1 = QtWidgets.QSlider(self.frame_js_control)
        self.slider_j1.setGeometry(QtCore.QRect(120, 120, 150, 40))
        self.slider_j1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_j1.setObjectName("slider_j1")
        self.input_j1 = QtWidgets.QLineEdit(self.frame_js_control)
        self.input_j1.setGeometry(QtCore.QRect(160, 70, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_j1.setFont(font)
        self.input_j1.setAlignment(QtCore.Qt.AlignCenter)
        self.input_j1.setObjectName("input_j1")
        self.input_j2 = QtWidgets.QLineEdit(self.frame_js_control)
        self.input_j2.setGeometry(QtCore.QRect(480, 70, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_j2.setFont(font)
        self.input_j2.setAlignment(QtCore.Qt.AlignCenter)
        self.input_j2.setObjectName("input_j2")
        self.input_j6 = QtWidgets.QLineEdit(self.frame_js_control)
        self.input_j6.setGeometry(QtCore.QRect(800, 180, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_j6.setFont(font)
        self.input_j6.setAlignment(QtCore.Qt.AlignCenter)
        self.input_j6.setObjectName("input_j6")
        self.input_j4 = QtWidgets.QLineEdit(self.frame_js_control)
        self.input_j4.setGeometry(QtCore.QRect(160, 180, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_j4.setFont(font)
        self.input_j4.setAlignment(QtCore.Qt.AlignCenter)
        self.input_j4.setObjectName("input_j4")
        self.slider_j2 = QtWidgets.QSlider(self.frame_js_control)
        self.slider_j2.setGeometry(QtCore.QRect(440, 120, 150, 40))
        self.slider_j2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_j2.setObjectName("slider_j2")
        self.label_j2 = QtWidgets.QLabel(self.frame_js_control)
        self.label_j2.setGeometry(QtCore.QRect(350, 120, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_j2.setFont(font)
        self.label_j2.setObjectName("label_j2")
        self.label_j3 = QtWidgets.QLabel(self.frame_js_control)
        self.label_j3.setGeometry(QtCore.QRect(670, 120, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_j3.setFont(font)
        self.label_j3.setObjectName("label_j3")
        self.label_j5 = QtWidgets.QLabel(self.frame_js_control)
        self.label_j5.setGeometry(QtCore.QRect(350, 230, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_j5.setFont(font)
        self.label_j5.setObjectName("label_j5")
        self.input_j3 = QtWidgets.QLineEdit(self.frame_js_control)
        self.input_j3.setGeometry(QtCore.QRect(800, 70, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_j3.setFont(font)
        self.input_j3.setAlignment(QtCore.Qt.AlignCenter)
        self.input_j3.setObjectName("input_j3")
        self.slider_j4 = QtWidgets.QSlider(self.frame_js_control)
        self.slider_j4.setGeometry(QtCore.QRect(120, 230, 150, 40))
        self.slider_j4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_j4.setObjectName("slider_j4")
        self.label_j6 = QtWidgets.QLabel(self.frame_js_control)
        self.label_j6.setGeometry(QtCore.QRect(670, 230, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_j6.setFont(font)
        self.label_j6.setObjectName("label_j6")
        self.label_j4 = QtWidgets.QLabel(self.frame_js_control)
        self.label_j4.setGeometry(QtCore.QRect(30, 230, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_j4.setFont(font)
        self.label_j4.setObjectName("label_j4")
        self.button_j3_minus = QtWidgets.QPushButton(self.frame_js_control)
        self.button_j3_minus.setGeometry(QtCore.QRect(760, 70, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_j3_minus.setFont(font)
        self.button_j3_minus.setObjectName("button_j3_minus")
        self.button_j1_plus = QtWidgets.QPushButton(self.frame_js_control)
        self.button_j1_plus.setGeometry(QtCore.QRect(230, 70, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_j1_plus.setFont(font)
        self.button_j1_plus.setObjectName("button_j1_plus")
        self.button_j4_plus = QtWidgets.QPushButton(self.frame_js_control)
        self.button_j4_plus.setGeometry(QtCore.QRect(230, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_j4_plus.setFont(font)
        self.button_j4_plus.setObjectName("button_j4_plus")
        self.button_j1_minus = QtWidgets.QPushButton(self.frame_js_control)
        self.button_j1_minus.setGeometry(QtCore.QRect(120, 70, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_j1_minus.setFont(font)
        self.button_j1_minus.setObjectName("button_j1_minus")
        self.button_j6_plus = QtWidgets.QPushButton(self.frame_js_control)
        self.button_j6_plus.setGeometry(QtCore.QRect(870, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_j6_plus.setFont(font)
        self.button_j6_plus.setObjectName("button_j6_plus")
        self.button_j6_minus = QtWidgets.QPushButton(self.frame_js_control)
        self.button_j6_minus.setGeometry(QtCore.QRect(760, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_j6_minus.setFont(font)
        self.button_j6_minus.setObjectName("button_j6_minus")
        self.button_j5_plus = QtWidgets.QPushButton(self.frame_js_control)
        self.button_j5_plus.setGeometry(QtCore.QRect(550, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_j5_plus.setFont(font)
        self.button_j5_plus.setObjectName("button_j5_plus")
        self.button_j5_minus = QtWidgets.QPushButton(self.frame_js_control)
        self.button_j5_minus.setGeometry(QtCore.QRect(440, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_j5_minus.setFont(font)
        self.button_j5_minus.setObjectName("button_j5_minus")
        self.button_j3_plus = QtWidgets.QPushButton(self.frame_js_control)
        self.button_j3_plus.setGeometry(QtCore.QRect(870, 70, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_j3_plus.setFont(font)
        self.button_j3_plus.setObjectName("button_j3_plus")
        self.button_j2_plus = QtWidgets.QPushButton(self.frame_js_control)
        self.button_j2_plus.setGeometry(QtCore.QRect(550, 70, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_j2_plus.setFont(font)
        self.button_j2_plus.setObjectName("button_j2_plus")
        self.button_j2_minus = QtWidgets.QPushButton(self.frame_js_control)
        self.button_j2_minus.setGeometry(QtCore.QRect(440, 70, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_j2_minus.setFont(font)
        self.button_j2_minus.setObjectName("button_j2_minus")
        self.button_j4_minus = QtWidgets.QPushButton(self.frame_js_control)
        self.button_j4_minus.setGeometry(QtCore.QRect(120, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_j4_minus.setFont(font)
        self.button_j4_minus.setObjectName("button_j4_minus")
        self.frame_variables = QtWidgets.QFrame(self.centralwidget)
        self.frame_variables.setGeometry(QtCore.QRect(0, 800, 960, 200))
        self.frame_variables.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_variables.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_variables.setObjectName("frame_variables")
        self.button_stop = QtWidgets.QPushButton(self.frame_variables)
        self.button_stop.setGeometry(QtCore.QRect(810, 45, 141, 60))
        self.button_stop.clicked.connect(self.stop)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_stop.setFont(font)
        self.button_stop.setObjectName("button_stop")
        self.button_home = QtWidgets.QPushButton(self.frame_variables)
        self.button_home.setGeometry(QtCore.QRect(810, 125, 141, 60))
        self.button_home.clicked.connect(self.home_button)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_home.setFont(font)
        self.button_home.setObjectName("button_home")
        self.button_start_record = QtWidgets.QPushButton(self.frame_variables)
        self.button_start_record.setGeometry(QtCore.QRect(650, 45, 141, 60))
        self.button_start_record.clicked.connect(self.start_record)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_start_record.setFont(font)
        self.button_start_record.setObjectName("button_start_record")
        self.button_start_repeat = QtWidgets.QPushButton(self.frame_variables)
        self.button_start_repeat.setGeometry(QtCore.QRect(650, 125, 141, 60))
        self.button_start_repeat.clicked.connect(self.start_repeat)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_start_repeat.setFont(font)
        self.button_start_repeat.setObjectName("button_start_repeat")
        self.label_variables = QtWidgets.QLabel(self.frame_variables)
        self.label_variables.setGeometry(QtCore.QRect(0, 0, 960, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_variables.setFont(font)
        self.label_variables.setAlignment(QtCore.Qt.AlignCenter)
        self.label_variables.setObjectName("label_variables")
        #self.button_set_variables = QtWidgets.QPushButton(self.frame_variables)
        #self.button_set_variables.setGeometry(QtCore.QRect(630, 60, 171, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        #self.button_set_variables.setFont(font)
        #self.button_set_variables.setObjectName("button_set_variables")
        self.label_ik_budget = QtWidgets.QLabel(self.frame_variables)
        self.label_ik_budget.setGeometry(QtCore.QRect(70, 120, 181, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_ik_budget.setFont(font)
        self.label_ik_budget.setObjectName("label_ik_budget")
        self.input_ik_budget = QtWidgets.QLineEdit(self.frame_variables)
        self.input_ik_budget.setGeometry(QtCore.QRect(270, 120, 51, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input_ik_budget.setFont(font)
        self.input_ik_budget.setObjectName("input_ik_budget")
        self.label_hertz_2 = QtWidgets.QLabel(self.frame_variables)
        self.label_hertz_2.setGeometry(QtCore.QRect(290, 120, 31, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_hertz_2.setFont(font)
        self.label_hertz_2.setText("")
        self.label_hertz_2.setObjectName("label_hertz_2")
        self.label_rest_2 = QtWidgets.QLabel(self.frame_variables)
        self.label_rest_2.setGeometry(QtCore.QRect(70, 60, 181, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_rest_2.setFont(font)
        self.label_rest_2.setObjectName("label_rest_2")
        self.input_step_size = QtWidgets.QLineEdit(self.frame_variables)
        self.input_step_size.setGeometry(QtCore.QRect(270, 60, 51, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input_step_size.setFont(font)
        self.input_step_size.setObjectName("input_step_size")
        self.label_rest = QtWidgets.QLabel(self.frame_variables)
        self.label_rest.setGeometry(QtCore.QRect(340, 60, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_rest.setFont(font)
        self.label_rest.setObjectName("label_rest")
        self.frame_rviz = QtWidgets.QFrame(self.centralwidget)
        self.frame_rviz.setGeometry(QtCore.QRect(960, 0, 960, 1080))
        self.frame_rviz.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_rviz.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rviz.setObjectName("frame_rviz")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 10, 960, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        MainWindow.setCentralWidget(self.centralwidget)
        

        #parameters
        #x-slider
        self.slider_x.valueChanged.connect(self.update_x_pos_slider)
        #x-line edit
        self.input_x_axis.returnPressed.connect(self.update_x_pos_text)
        #x - +- buttons
        self.button_x_plus.clicked.connect(self.update_x_pos_button_plus)
        self.button_x_minus.clicked.connect(self.update_x_pos_button_minus)
        #y-slider
        self.slider_y.valueChanged.connect(self.update_y_pos_slider)
        #y-line edit
        self.input_y_axis.returnPressed.connect(self.update_y_pos_text)
        #y - +- buttons
        self.button_y_plus.clicked.connect(self.update_y_pos_button_plus)
        self.button_y_minus.clicked.connect(self.update_y_pos_button_minus)
        #z-slider
        self.slider_z.valueChanged.connect(self.update_z_pos_slider)
        #z-line edit
        self.input_z_axis.returnPressed.connect(self.update_z_pos_text)
        #z - +- buttons
        self.button_z_plus.clicked.connect(self.update_z_pos_button_plus)
        self.button_z_minus.clicked.connect(self.update_z_pos_button_minus)
        #phi-slider
        self.slider_phi.setRange(-360, 360)
        self.slider_phi.setSliderPosition(0)
        self.slider_phi.valueChanged.connect(self.update_phi_pos_slider)
        #phi-line edit
        self.input_phi.returnPressed.connect(self.update_phi_pos_text)
        #phi - +- buttons
        self.button_phi_plus.clicked.connect(self.update_phi_pos_button_plus)
        self.button_phi_minus.clicked.connect(self.update_phi_pos_button_minus)
        #theta-slider
        self.slider_theta.setRange(-360, 360)
        self.slider_theta.setSliderPosition(0)
        self.slider_theta.valueChanged.connect(self.update_theta_pos_slider)
        #theta-line edit
        self.input_theta.returnPressed.connect(self.update_theta_pos_text)
        #theta - +- buttons
        self.button_theta_plus.clicked.connect(self.update_theta_pos_button_plus)
        self.button_theta_minus.clicked.connect(self.update_theta_pos_button_minus)
        #psi-slider
        self.slider_psi.setRange(-360, 360)
        self.slider_psi.setSliderPosition(0)
        self.slider_psi.valueChanged.connect(self.update_psi_pos_slider)
        #psi-line edit
        self.input_psi.returnPressed.connect(self.update_psi_pos_text)
        #psi - +- buttons
        self.button_psi_plus.clicked.connect(self.update_psi_pos_button_plus)
        self.button_psi_minus.clicked.connect(self.update_psi_pos_button_minus)

        #j1-slider
        self.slider_j1.setRange(-360, 360)
        self.slider_j1.setSliderPosition(0)
        self.slider_j1.valueChanged.connect(self.update_j1_pos_slider)
        #j1-line edit
        self.input_j1.returnPressed.connect(self.update_j1_pos_text)
        #j1 - +- buttons
        self.button_j1_plus.clicked.connect(self.update_j1_pos_button_plus)
        self.button_j1_minus.clicked.connect(self.update_j1_pos_button_minus)

        #j2-slider
        self.slider_j2.setRange(-360, 360)
        self.slider_j2.setSliderPosition(0)
        self.slider_j2.valueChanged.connect(self.update_j2_pos_slider)
        #j2-line edit
        self.input_j2.returnPressed.connect(self.update_j2_pos_text)
        #j2 - +- buttons
        self.button_j2_plus.clicked.connect(self.update_j2_pos_button_plus)
        self.button_j2_minus.clicked.connect(self.update_j2_pos_button_minus)

        #j3-slider
        self.slider_j3.setRange(-360, 360)
        self.slider_j3.setSliderPosition(0)
        self.slider_j3.valueChanged.connect(self.update_j3_pos_slider)
        #j3-line edit
        self.input_j3.returnPressed.connect(self.update_j3_pos_text)
        #j3 - +- buttons
        self.button_j3_plus.clicked.connect(self.update_j3_pos_button_plus)
        self.button_j3_minus.clicked.connect(self.update_j3_pos_button_minus)

        #j4-slider
        self.slider_j4.setRange(-360, 360)
        self.slider_j4.setSliderPosition(0)
        self.slider_j4.valueChanged.connect(self.update_j4_pos_slider)
        #j4-line edit
        self.input_j4.returnPressed.connect(self.update_j4_pos_text)
        #j4 - +- buttons
        self.button_j4_plus.clicked.connect(self.update_j4_pos_button_plus)
        self.button_j4_minus.clicked.connect(self.update_j4_pos_button_minus)

        #j5-slider
        self.slider_j5.setRange(-360, 360)
        self.slider_j5.setSliderPosition(0)
        self.slider_j5.valueChanged.connect(self.update_j5_pos_slider)
        #j5-line edit
        self.input_j5.returnPressed.connect(self.update_j5_pos_text)
        #j5 - +- buttons
        self.button_j5_plus.clicked.connect(self.update_j5_pos_button_plus)
        self.button_j5_minus.clicked.connect(self.update_j5_pos_button_minus)

        #j6-slider
        self.slider_j6.setRange(-360, 360)
        self.slider_j6.setSliderPosition(0)
        self.slider_j6.valueChanged.connect(self.update_j6_pos_slider)
        #j6-line edit
        self.input_j6.returnPressed.connect(self.update_j6_pos_text)
        #j6 - +- buttons
        self.button_j6_plus.clicked.connect(self.update_j6_pos_button_plus)
        self.button_j6_minus.clicked.connect(self.update_j6_pos_button_minus)

        #ik iterations-line edit
        self.input_ik_budget.returnPressed.connect(self.set_ik_optimizer_budget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robot Controller"))
        self.input_com_port.setText(_translate("MainWindow", "COM7"))
        self.label_serial_port.setText(_translate("MainWindow", "Serial Port:"))
        self.button_connect_uart.setText(_translate("MainWindow", "Connect"))
        self.button_disconnect_uart.setText(_translate("MainWindow", "Disconnect"))
        self.label_ts_control.setText(_translate("MainWindow", "Task Space Control"))
        self.label_x.setText(_translate("MainWindow", "X-Axis:"))
        self.input_x_axis.setText(_translate("MainWindow", "0.0"))
        self.input_y_axis.setText(_translate("MainWindow", "0.0"))
        self.label_y.setText(_translate("MainWindow", "Y-Axis:"))
        self.input_z_axis.setText(_translate("MainWindow", "0.0"))
        self.label_z.setText(_translate("MainWindow", "Z-Axis:"))
        self.label_theta.setText(_translate("MainWindow", "THETA:"))
        self.input_phi.setText(_translate("MainWindow", "0.0"))
        self.input_psi.setText(_translate("MainWindow", "0.0"))
        self.label_psi.setText(_translate("MainWindow", "PSI:"))
        self.input_theta.setText(_translate("MainWindow", "0.0"))
        self.label_phi.setText(_translate("MainWindow", "PHI:"))
        self.button_x_plus.setText(_translate("MainWindow", "+"))
        self.button_y_plus.setText(_translate("MainWindow", "+"))
        self.button_z_plus.setText(_translate("MainWindow", "+"))
        self.button_phi_plus.setText(_translate("MainWindow", "+"))
        self.button_theta_plus.setText(_translate("MainWindow", "+"))
        self.button_psi_plus.setText(_translate("MainWindow", "+"))
        self.button_x_minus.setText(_translate("MainWindow", "-"))
        self.button_y_minus.setText(_translate("MainWindow", "-"))
        self.button_z_minus.setText(_translate("MainWindow", "-"))
        self.button_psi_minus.setText(_translate("MainWindow", "-"))
        self.button_theta_minus.setText(_translate("MainWindow", "-"))
        self.button_phi_minus.setText(_translate("MainWindow", "-"))
        self.label_js_control.setText(_translate("MainWindow", "Joint Space Control"))
        self.input_j5.setText(_translate("MainWindow", "0.0"))
        self.label_j1.setText(_translate("MainWindow", "Joint 1:"))
        self.input_j1.setText(_translate("MainWindow", "0.0"))
        self.input_j2.setText(_translate("MainWindow", "0.0"))
        self.input_j6.setText(_translate("MainWindow", "0.0"))
        self.input_j4.setText(_translate("MainWindow", "0.0"))
        self.label_j2.setText(_translate("MainWindow", "Joint 2:"))
        self.label_j3.setText(_translate("MainWindow", "Joint 3:"))
        self.label_j5.setText(_translate("MainWindow", "Joint 5:"))
        self.input_j3.setText(_translate("MainWindow", "0.0"))
        self.label_j6.setText(_translate("MainWindow", "Joint 6:"))
        self.label_j4.setText(_translate("MainWindow", "Joint 4:"))
        self.button_j3_minus.setText(_translate("MainWindow", "-"))
        self.button_j1_plus.setText(_translate("MainWindow", "+"))
        self.button_j4_plus.setText(_translate("MainWindow", "+"))
        self.button_j1_minus.setText(_translate("MainWindow", "-"))
        self.button_j6_plus.setText(_translate("MainWindow", "+"))
        self.button_j6_minus.setText(_translate("MainWindow", "-"))
        self.button_j5_plus.setText(_translate("MainWindow", "+"))
        self.button_j5_minus.setText(_translate("MainWindow", "-"))
        self.button_j3_plus.setText(_translate("MainWindow", "+"))
        self.button_j2_plus.setText(_translate("MainWindow", "+"))
        self.button_j2_minus.setText(_translate("MainWindow", "-"))
        self.button_j4_minus.setText(_translate("MainWindow", "-"))
        self.button_stop.setText(_translate("MainWindow", "STOP"))
        self.button_home.setText(_translate("MainWindow", "HOME"))
        self.button_start_record.setText(_translate("MainWindow", "Record"))
        self.button_start_repeat.setText(_translate("MainWindow", "Repeat"))
        self.label_variables.setText(_translate("MainWindow", "Variables"))
        #self.button_set_variables.setText(_translate("MainWindow", "Set Variables"))
        self.label_ik_budget.setText(_translate("MainWindow", "IK budget:"))
        self.input_ik_budget.setText(_translate("MainWindow", "100"))
        self.label_rest_2.setText(_translate("MainWindow", "Step Size:"))
        self.input_step_size.setText(_translate("MainWindow", "10"))
        self.label_rest.setText(_translate("MainWindow", "mm/deg"))
        self.input_step_size.returnPressed.connect(self.update_step_size)
        self.title.setText(_translate("MainWindow", "6 DOF-Robot Controller"))

    def connect_uart_clicked(self):
        print("Connecting UART.....")

    def disconnect_uart_clicked(self):
        print("Disconnecting UART....")

    def update_x_pos_slider(self):
        if (np.linalg.norm(self.x_pos-self.slider_x.value()) >= 0.1 and not self.init_run):
            self.x_pos = self.slider_x.value()
            self.calcInverseKinematics()
        self.input_x_axis.setText(str(float(self.slider_x.value())))
        self.setFocus()
        
    def update_x_pos_button_plus(self):
        self.slider_x.setValue(int(self.x_pos + self.step_size))

    def update_x_pos_button_minus(self):
        self.slider_x.setValue(int(self.x_pos - self.step_size))

    def update_x_pos_text(self):
        self.slider_x.setValue(int(self.input_x_axis.text()))

    def update_y_pos_slider(self):
        if (np.linalg.norm(self.y_pos-self.slider_y.value()) >= 0.1 and not self.init_run):
            self.y_pos = self.slider_y.value()
            self.calcInverseKinematics()
        self.input_y_axis.setText(str(float(self.slider_y.value())))
        self.setFocus()
        
    def update_y_pos_button_plus(self):
        self.slider_y.setValue(int(self.y_pos + self.step_size))

    def update_y_pos_button_minus(self):
        self.slider_y.setValue(int(self.y_pos - self.step_size))

    def update_y_pos_text(self):
        self.slider_y.setValue(int(self.input_y_axis.text()))

    def update_z_pos_slider(self):
        if (np.linalg.norm(self.z_pos-self.slider_z.value()) >= 0.1 and not self.init_run):
            self.z_pos = self.slider_z.value()
            self.calcInverseKinematics()
        self.input_z_axis.setText(str(float(self.slider_z.value())))
        self.setFocus()
        
    def update_z_pos_button_plus(self):
        self.slider_z.setValue(int(self.z_pos + self.step_size))

    def update_z_pos_button_minus(self):
        self.slider_z.setValue(int(self.z_pos - self.step_size))

    def update_z_pos_text(self):
        self.slider_z.setValue(int(self.input_z_axis.text()))

    def update_phi_pos_slider(self):
        if (np.linalg.norm(self.phi_pos-self.slider_phi.value()) >= 0.1 and not self.init_run):
            self.phi_pos = self.slider_phi.value()
            self.calcInverseKinematics()
        self.input_phi.setText(str(float(self.slider_phi.value())))
        self.setFocus()
        
    def update_phi_pos_button_plus(self):
        self.slider_phi.setValue(int(self.phi_pos + self.step_size))

    def update_phi_pos_button_minus(self):
        self.slider_phi.setValue(int(self.phi_pos - self.step_size))

    def update_phi_pos_text(self):
        self.slider_phi.setValue(int(self.input_phi.text()))

    def update_theta_pos_slider(self):
        if (np.linalg.norm(self.theta_pos-self.slider_theta.value()) >= 0.1 and not self.init_run):
            self.theta_pos = self.slider_theta.value()
            self.calcInverseKinematics()
        self.input_theta.setText(str(float(self.slider_theta.value())))
        self.setFocus()
        
    def update_theta_pos_button_plus(self):
        self.slider_theta.setValue(int(self.theta_pos + self.step_size))

    def update_theta_pos_button_minus(self):
        self.slider_theta.setValue(int(self.theta_pos - self.step_size))

    def update_theta_pos_text(self):
        self.slider_theta.setValue(int(self.input_theta.text()))

    def update_psi_pos_slider(self):
        if (np.linalg.norm(self.psi_pos-self.slider_psi.value()) >= 0.1 and not self.init_run):
            self.psi_pos = self.slider_psi.value()
            self.calcInverseKinematics()
        self.input_psi.setText(str(float(self.slider_psi.value())))
        self.setFocus()
        
    def update_psi_pos_button_plus(self):
        self.slider_psi.setValue(int(self.psi_pos + self.step_size))

    def update_psi_pos_button_minus(self):
        self.slider_psi.setValue(int(self.psi_pos - self.step_size))

    def update_psi_pos_text(self):
        self.slider_psi.setValue(int(self.input_psi.text()))

    def update_j1_pos_slider(self):
        self.input_j1.setText(str(float(self.slider_j1.value())))
        self.setFocus()

    def update_j1_pos_button_plus(self):
        self.slider_j1.setValue(int(self.j1_pos + self.step_size))

    def update_j1_pos_button_minus(self):
        self.slider_j1.setValue(int(self.j1_pos - self.step_size))

    def update_j1_pos_text(self):
        self.slider_j1.setValue(int(self.input_j1.text()))

    def update_j2_pos_slider(self):
        self.input_j2.setText(str(float(self.slider_j2.value())))
        self.setFocus()

    def update_j2_pos_button_plus(self):
        self.slider_j2.setValue(int(self.j2_pos + self.step_size))

    def update_j2_pos_button_minus(self):
        self.slider_j2.setValue(int(self.j2_pos - self.step_size))

    def update_j2_pos_text(self):
        self.slider_j2.setValue(int(self.input_j2.text()))

    def update_j3_pos_slider(self):
        self.input_j3.setText(str(float(self.slider_j3.value())))
        self.setFocus()

    def update_j3_pos_button_plus(self):
        self.slider_j3.setValue(int(self.j3_pos + self.step_size))

    def update_j3_pos_button_minus(self):
        self.slider_j3.setValue(int(self.j3_pos - self.step_size))

    def update_j3_pos_text(self):
        self.slider_j3.setValue(int(self.input_j3.text()))
    
    def update_j4_pos_slider(self):
        self.input_j4.setText(str(float(self.slider_j4.value())))
        self.setFocus()

    def update_j4_pos_button_plus(self):
        self.slider_j4.setValue(int(self.j4_pos + self.step_size))

    def update_j4_pos_button_minus(self):
        self.slider_j4.setValue(int(self.j4_pos - self.step_size))

    def update_j4_pos_text(self):
        self.slider_j4.setValue(int(self.input_j4.text()))

    def update_j5_pos_slider(self):
        self.input_j5.setText(str(float(self.slider_j5.value())))
        self.setFocus()

    def update_j5_pos_button_plus(self):
        self.slider_j5.setValue(int(self.j5_pos + self.step_size))

    def update_j5_pos_button_minus(self):
        self.slider_j5.setValue(int(self.j5_pos - self.step_size))

    def update_j5_pos_text(self):
        self.slider_j5.setValue(int(self.input_j5.text()))

    def update_j6_pos_slider(self):
        self.input_j6.setText(str(float(self.slider_j6.value())))
        self.setFocus()

    def update_j6_pos_button_plus(self):
        self.slider_j6.setValue(int(self.j6_pos + self.step_size))

    def update_j6_pos_button_minus(self):
        self.slider_j6.setValue(int(self.j6_pos - self.step_size))

    def update_j6_pos_text(self):
        self.slider_j6.setValue(int(self.input_j6.text()))

    def home_button(self):
        self.init_run = True
        self.ik = np.asarray(self.zero_pos, dtype=float)
        self.init_position()
        self.ax.cla() 
        self.ax.set_xlim3d(-0.2, 0.2)
        self.ax.set_ylim3d(-0.2, 0.2)
        self.ax.set_zlim(0, 0.3)
        self.ax.set_xlabel('X [m]')
        self.ax.set_ylabel('Y [m]')
        self.ax.set_zlabel('Z [m]')
        self.ax.grid(False)
        self.ax.xaxis.pane.fill = False
        self.ax.yaxis.pane.fill = False
        self.ax.zaxis.pane.fill = False
        self.my_chain.plot(self.ik, self.ax, target=None)
        self.pos_error = "Positional Error: " + str(0.0)
        self.ax.set_title(self.pos_error)
        self.fig.canvas.draw()
        self.fig.canvas.flush_events()
        self.j1_pos = self.j1_zero_pos
        self.j2_pos = self.j2_zero_pos
        self.j3_pos = self.j3_zero_pos
        self.j4_pos = self.j4_zero_pos
        self.j5_pos = self.j5_zero_pos
        self.j6_pos = self.j6_zero_pos
        self.x_pos = self.x_zero_pos
        self.y_pos = self.y_zero_pos
        self.z_pos = self.z_zero_pos
        self.phi_pos = self.phi_zero_pos
        self.theta_pos = self.theta_zero_pos
        self.psi_pos = self.psi_zero_pos

    def update_step_size(self):
        self.step_size = int(self.input_step_size.text())
        self.setFocus()

    def set_ik_optimizer_budget(self):
        self.ik_optimizer_budget = int(self.input_ik_budget.text())
        print("IK optimizer budget updated: %d" % self.ik_optimizer_budget)

    def stop(self):
        self.stopRecord = True
        self.stopRepeat = True

    def start_record(self):
        self.stopRecord = False
        self.record_thread()

    def start_repeat(self):
        self.stopRepeat = False
        self.repeat_thread()
